# Generated by Django 5.0.7 on 2024-08-04 10:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('birth_year', models.IntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2024)])),
                ('phone_number', models.CharField(max_length=20)),
                ('appointment_date', models.DateField()),
                ('appointment_time', models.TimeField()),
                ('source', models.CharField(choices=[('Telegram', 'Telegram'), ('Instagram', 'Instagram'), ('doctor_recommendation', 'Doctor Recommendation'), ('regular_customer', 'Regular Customer'), ('friend_recommendation', 'Friend Recommendation')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='ClinicSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('time_interval', models.IntegerField(default=10, help_text='Time interval in minutes')),
            ],
        ),
    ]
