# Generated by Django 5.0.7 on 2024-08-05 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='appointment',
            unique_together={('appointment_date', 'appointment_time')},
        ),
    ]
