# Generated by Django 5.0.7 on 2024-08-05 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0002_alter_appointment_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicsettings',
            name='admission_name',
            field=models.CharField(default="Ko'z qabuli uchun forma", max_length=100),
            preserve_default=False,
        ),
    ]
