# Generated by Django 5.0.7 on 2024-08-05 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0003_clinicsettings_admission_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='called',
            field=models.BooleanField(default=False),
        ),
    ]
